AWSTemplateFormatVersion: '2010-09-09'
Description: Generic launch template

Parameters:
  Application:
    Type: String
    Description: Application this template belongs to
    Default: DefaultApp

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        -
          Fn::ImportValue:
            !Sub '${Application}-GenericEC2Role-Name'

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: !Ref LatestAmiId
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: "user:project", Value: !Ref Application }
          - ResourceType: volume
            Tags:
              - { Key: "user:project", Value: !Ref Application }

      LaunchTemplateName: !Sub '${AWS::StackName}-LaunchTemplate'

  InstancesSSMResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Description: !Sub Resource group of ${Application} EC2 instances
      Name: !Ref Application
      ResourceQuery:
        Query:
          ResourceTypeFilters:
            - AWS::EC2::Instance
          TagFilters:
            - { Key: "user:project", Values: [ !Ref Application ]}
        Type: TAG_FILTERS_1_0
      Tags:
        - { Key: "user:project", Value: !Ref Application }

  CloudWatchSSMAssociation:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: !Sub '${Application}-CloudWatchSSMAssociation'
      ComplianceSeverity: HIGH
      Name: AWS-ConfigureAWSPackage
      Parameters:
        action: ["Install"]
        installationType: ["Uninstall and reinstall"]
        name: ["AmazonCloudWatchAgent"]
      ScheduleExpression: "rate(1 day)"
      Targets:
        - Key: resource-groups:Name
          Values:
            - !Ref InstancesSSMResourceGroup

  CodeDeploySSMAssociation:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: !Sub '${Application}-CodeDeploySSMAssociation'
      ComplianceSeverity: HIGH
      Name: AWS-ConfigureAWSPackage
      Parameters:
        action: ["Install"]
        installationType: ["Uninstall and reinstall"]
        name: ["AWSCodeDeployAgent"]
      ScheduleExpression: "rate(1 day)"
      Targets:
        - Key: resource-groups:Name
          Values:
            - !Ref InstancesSSMResourceGroup

Outputs:
  EC2InstanceProfile:
    Description: Generic EC2 instance profile
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfile'

  LaunchTemplate:
    Description: Generic EC2 launch template Id
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-Id'
